server:
  port: 80
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://com-mysql:3306/community?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: root
  mvc:
    static-path-pattern: /**
  redis:
    database: 0
    host: com-redis
    port: 6379
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-path}
logging:
  file:
    max-history: 20
    max-size: 100MB
    name: logs/comm.log
  level:
    root: info
    life.liudong.community.mapper: DEBUG
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: life.liudong.community.model.mapper
github:
  client:
    id: 40cca80d10082a99e683
    secret: 3fa26c1e1bdff4a6e6fc48ea1101ef1b7e392646
  redirect:
    url: http://thinkingshare.icu/callback
image:
  server:
    url: /file-server/image/
web:
  upload-path: /file-server/

